<?php

use App\SubmitPro;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $property=SubmitPro::create([
            'pics1'=> 'a1.jpg',
            'pics2'=> '10.jpg',
            'pics3'=> '11.jpg',
            'pname' => 'Simple Best  Villaa',
            'pprice' => '96587412363',
            'pbuilt' => '2000',
            'phone2' => '9925243238',
            'email' => 'user@gmail.com',
            'pdesc' => 'Property is So nice',
            'country' => 'India',
            'state' => 'Gujrat',
            'city' => 'Junagadh',
            'storeroom' => 'None',
            'bedroom' => '1',
            'bathroom' => '1',
            'parking' => 'None',
            'ac' => 'AC',
            'kitchen' => 'Yes',
            'garden' => 'No',
            'spool' => 'No',
            'garages' => 'No',
            'pstatus' => 'Sell',
            'termes' => 'on',
        ]);
        $property1=SubmitPro::create([
            'pics1'=> 'a2.jpg',
            'pics2'=> '12.jpg',
            'pics3'=> '13.jpg',
            'pname' => 'Simple Best  Villaa',
            'pprice' => '96587412363',
            'pbuilt' => '2000',
            'phone2' => '9925243238',
            'email' => 'user@gmail.com',
            'pdesc' => 'Property is So nice',
            'country' => 'India',
            'state' => 'Gujrat',
            'city' => 'Junagadh',
            'storeroom' => 'None',
            'bedroom' => '1',
            'bathroom' => '1',
            'parking' => 'None',
            'ac' => 'AC',
            'kitchen' => 'Yes',
            'garden' => 'No',
            'spool' => 'No',
            'garages' => 'No',
            'pstatus' => 'Sell',
            'termes' => 'on',
        ]);
        $property2=SubmitPro::create([
            'pics1'=> 'a3.jpg',
            'pics2'=> '14.jpg',
            'pics3'=> '15.jpg',
            'pname' => 'Simple Best  Villaa',
            'pprice' => '96587412363',
            'pbuilt' => '2000',
            'phone2' => '9925243238',
            'email' => 'user@gmail.com',
            'pdesc' => 'Property is So nice',
            'country' => 'India',
            'state' => 'Gujrat',
            'city' => 'Junagadh',
            'storeroom' => 'None',
            'bedroom' => '1',
            'bathroom' => '1',
            'parking' => 'None',
            'ac' => 'AC',
            'kitchen' => 'Yes',
            'garden' => 'No',
            'spool' => 'No',
            'garages' => 'No',
            'pstatus' => 'Sell',
            'termes' => 'on',
        ]);
        $property3=SubmitPro::create([
            'pics1'=> 'a4.jpg',
            'pics2'=> '16.jpg',
            'pics3'=> '17.jpg',
            'pname' => 'Simple Best  Villaa',
            'pprice' => '96587412363',
            'pbuilt' => '2000',
            'phone2' => '9925243238',
            'email' => 'user@gmail.com',
            'pdesc' => 'Property is So nice',
            'country' => 'India',
            'state' => 'Gujrat',
            'city' => 'Junagadh',
            'storeroom' => 'None',
            'bedroom' => '1',
            'bathroom' => '1',
            'parking' => 'None',
            'ac' => 'AC',
            'kitchen' => 'Yes',
            'garden' => 'No',
            'spool' => 'No',
            'garages' => 'No',
            'pstatus' => 'Sell',
            'termes' => 'on',
        ]);
        $property4=SubmitPro::create([
            'pics1'=> 'a5.jpg',
            'pics2'=> '18.jpg',
            'pics3'=> '19.jpg',
            'pname' => 'Simple Best  Villaa',
            'pprice' => '96587',
            'pbuilt' => '2000',
            'phone2' => '9925243238',
            'email' => 'user@gmail.com',
            'pdesc' => 'Property is So nice',
            'country' => 'India',
            'state' => 'Gujrat',
            'city' => 'Junagadh',
            'storeroom' => 'None',
            'bedroom' => '1',
            'bathroom' => '1',
            'parking' => 'None',
            'ac' => 'AC',
            'kitchen' => 'Yes',
            'garden' => 'No',
            'spool' => 'No',
            'garages' => 'No',
            'pstatus' => 'Rent',
            'termes' => 'on',
        ]);
        $property5=SubmitPro::create([
            'pics1'=> 'a6.jpg',
            'pics2'=> '20.jpg',
            'pics3'=> '21.jpg',
            'pname' => 'Simple Best  Villaa',
            'pprice' => '96587',
            'pbuilt' => '2000',
            'phone2' => '9925243238',
            'email' => 'user@gmail.com',
            'pdesc' => 'Property is So nice',
            'country' => 'India',
            'state' => 'Gujrat',
            'city' => 'Junagadh',
            'storeroom' => 'None',
            'bedroom' => '1',
            'bathroom' => '1',
            'parking' => 'None',
            'ac' => 'AC',
            'kitchen' => 'Yes',
            'garden' => 'No',
            'spool' => 'No',
            'garages' => 'No',
            'pstatus' => 'Rent',
            'termes' => 'on',
        ]);
        $property6=SubmitPro::create([
            'pics1'=> 'a7.jpg',
            'pics2'=> '22.jpg',
            'pics3'=> '23.jpg',
            'pname' => 'Simple Best  Villaa',
            'pprice' => '96587',
            'pbuilt' => '2000',
            'phone2' => '9925243238',
            'email' => 'user@gmail.com',
            'pdesc' => 'Property is So nice',
            'country' => 'India',
            'state' => 'Gujrat',
            'city' => 'Junagadh',
            'storeroom' => 'None',
            'bedroom' => '1',
            'bathroom' => '1',
            'parking' => 'None',
            'ac' => 'AC',
            'kitchen' => 'Yes',
            'garden' => 'No',
            'spool' => 'No',
            'garages' => 'No',
            'pstatus' => 'Rent',
            'termes' => 'on',
        ]);
        $property7=SubmitPro::create([
            'pics1'=> 'a8.jpg',
            'pics2'=> '24.jpg',
            'pics3'=> '25.jpg',
            'pname' => 'Simple Best  Villaa',
            'pprice' => '9658',
            'pbuilt' => '2000',
            'phone2' => '9925243238',
            'email' => 'user@gmail.com',
            'pdesc' => 'Property is So nice',
            'country' => 'India',
            'state' => 'Gujrat',
            'city' => 'Junagadh',
            'storeroom' => 'None',
            'bedroom' => '1',
            'bathroom' => '1',
            'parking' => 'None',
            'ac' => 'AC',
            'kitchen' => 'Yes',
            'garden' => 'No',
            'spool' => 'No',
            'garages' => 'No',
            'pstatus' => 'Rent',
            'termes' => 'on',
        ]);
    }
}
